### ISSUE TITLE
Syzygy probing always returns dtz 0 in KvK for antichess

### ISSUE THREAD

**Issue by Torom** [niklasf/python-chess#929] opened 2022-10-17 16:45 UTC
Hey, if you probe a KvK position in antichess, it always returns dtz 0, even if there are no antichess tablebases at all. I would have expected a `MissingTableError` exception.

I would guess the error is in these lines: https://github.com/niklasf/python-chess/blob/5fc7298a1920d175061f9dae83373330be0b1035/chess/syzygy.py#L1573-L1575

Code to reproduce:
```python
import chess.variant
import chess.syzygy

board = chess.variant.AntichessBoard('8/8/8/8/8/3K4/8/4k3 w - - 0 30')
with chess.syzygy.open_tablebase('/path/to/syzygy') as tablebase:
    print(tablebase.probe_dtz(board))
```

**Comment by niklasf** [comment] 2022-10-17 17:59
Hi, thanks for reporting.

The issue is that the tablebase was not opened for the variant: https://python-chess.readthedocs.io/en/latest/variant.html#syzygy. I now added a check to correctly raise `KeyError` if the variant of the `board` does not match the variant of the tablebase.

One more surprise: Some Antichess positions can be resolved in the threat-search or 1-ply search, even if no tables exist. For example

```python
import chess.variant
import chess.syzygy

board = chess.variant.AntichessBoard('8/8/8/8/8/3K4/8/4k3 w - - 0 30')
with chess.syzygy.open_tablebase('/path/to/syzygy', VariantBoard=chess.variant.AntichessBoard) as tablebase:
    print(tablebase.probe_dtz(board))
```
correctly prints `2`.

**Closed by niklasf** 2022-10-17 17:59 UTC
Labels: bug
