### ISSUE TITLE
popen_uci 

### ISSUE THREAD

**Issue by ChrisWhittington** [niklasf/python-chess#689] opened 2020-11-04 20:46 UTC
Hi, I have a uci compliant (well, hopefully) engine that won't behave with popen_uci at initialisation.

Logger shows
connection made
<< uci

but no return of engine id, author etc.

the popen_uci code works fine with other test engines and my engine works fine with, for example, cutechess ui.

Is there a possibly that Python-Chess doesn't like file handling operations between sending "uci" and getting back id and readyok etc?

Reason I ask, is that when my own 'dump all uci comms' to HD tool was turned on to try and track this down, its file handler failed when trying to open a file for "w".

**Comment by niklasf** [comment] 2020-11-05 10:46
Duplicate of #690.

**Closed by niklasf** 2020-11-05 10:46 UTC
